sequenceDiagram
    participant browser
    participant server

    Note right of browser: User writes new note "Diagrama de secuencia" 

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    Note left of server: Server saves the new note in the database

    server-->>browser: 201 Created
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: New note added    
    deactivate server

    Note right of browser: Browser adds new note to list rendered in the page